{% set name = "clikit" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6819a5b2a78523be485ea9e1ef380ae8d02da4bffed540f7881fdaafbff41390

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - poetry >=0.12
# clikit need poetry to build
# pip install clikit==0.3.2 --no-binary :all:

  run:
    - pastel >=0.1.0,<0.2.0
    - pylev >=1.3,<2.0
    - python

test:
  imports:
    - clikit

about:
  home: https://github.com/sdispater/clikit
  license: MIT
  license_family: MIT
  license_file: LICENSE 
  summary: "CliKit is a group of utilities to build beautiful and testable command line interfaces."

extra:
  recipe-maintainers:
    - roccqqck
    
