{% set name = "sentencepiece" %} 
{% set version = "0.1.83" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/e8/cf/7089b87fdae8f47be81ce8e2e6377b321805c4648f2eb12fbd2987388dac/sentencepiece-0.1.83-cp37-cp37m-manylinux1_x86_64.whl
  sha256: 4daf9930f5e8882e09b6b1052614ab02e7db40ca83032160d49e7956e447d1f4

build:
  number: 1
  script:
    - python -m pip install --no-deps --ignore-installed ./sentencepiece-0.1.83-cp37-cp37m-manylinux1_x86_64.whl

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  import:
    - sentencepiece

about:
  home: "https://github.com/google/sentencepiece"
  license: "Apache-2.0"
  license_family: "Apache"
  license_file: ""
  summary: ""
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - roccqqck
