{% set name = "transformers" %}
{% set version = "2.1.1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/huggingface/transformers/archive/master.zip
  sha256: 7fd46d95bcc7b7e780c03c17d79f7f780fdea4c6b4617632ea7077fce188c854
# 2019-10-25
# https://github.com/huggingface/transformers/commit/ae1d03fc51bb22ed59517ee6f92c560417fdb049

build:
  noarch: python
  number: 0
  entry_points:
    - transformers=transformers.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - boto3
    - numpy
    - python
    - regex
    - requests
    - sacremoses
    - tqdm

test:
  imports:
    - transformers
    - transformers.data
    - transformers.data.metrics
    - transformers.data.processors
  commands:
    - transformers --help
  requires:
    - pytest

about:
  home: "https://github.com/huggingface/transformers"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - roccqqck
